[package]
name = "pollard-kangaroo"
version = "0.1.0"
edition = "2021"

[features]
default = []
generation = []

[dependencies]
curve25519-dalek-ng = { version = "4" }
anyhow = { version = "1.0", default-features = false }
rand = "0.8"
rand_core = { version = "0.6", default-features = false }
hex = "0.4.3"
